id: P007059
initial_creation_type: ocr
source_metadata:
  id: bdr:W2CZ7729
  title: བློ་རིགས་ཀྱི་རྣམ་གཞག་ཉེར་མཁོ་ཀུན་བཏུས
  author: ''
  volumes:
    c2535b27055444cd8bb4014adace29fd:
      image_group_id: I1KG2255
      title: ''
      volume_number: 1
      total_pages: 342
ebook_metadata:
  title: བློ་རིགས་ཀྱི་རྣམ་གཞག་ཉེར་མཁོ་ཀུན་བཏུས
  author: ''
  sku: P007059
  cover: cover.jpg
  layers:
  - pagination
