id: P007059
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W2CZ7729
  title: བློ་རིགས་ཀྱི་རྣམ་གཞག་ཉེར་མཁོ་ཀུན་བཏུས
  author: ''
  volumes:
    3db9375165274bcd9efcdf0f563c5343:
      image_group_id: I1KG2255
      title: Volume 1 of blo rigs gi rnam gzhag nyer mkho kun btus
      volume_number: 1
      total_pages: 342
      base_file: v001.txt
