id: I5B040004
legacy_id: P007059
ocr_import_info:
  bdrc_scan_id: W2CZ7729
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T14:51:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:17:26.479421+00:00'
last_modified: 2022-09-02 23:18:06.356174
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7729
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7729
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: བློ་རིགས་ཀྱི་རྣམ་གཞག་ཉེར་མཁོ་ཀུན་བཏུས།
  author: ཕུ་ཁང་དགེ་བཤེས་བློ་བཟང་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9137547315270504
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG2255:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG2255
      total_pages: 342
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG2255.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.9137547315270504
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
